utils::globalVariables(c("label",
                         "prop",
                         "change",
                         "file_name",
                         "level",
                         "what_lag",
                         "description",
                         "group",
                         "value"))
